[2023-06-01T18:22:02.697+0000] {processor.py:157} INFO - Started process (PID=23) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:02.697+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:22:02.698+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:22:02.698+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:02.700+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:22:02.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from CSV2DELTA.utils import CsvDagWrapper
ModuleNotFoundError: No module named 'CSV2DELTA'
[2023-06-01T18:22:02.700+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:02.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.021 seconds
[2023-06-01T18:22:32.819+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:32.819+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:22:32.819+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:22:32.819+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:32.821+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:22:32.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from CSV2DELTA.utils import CsvDagWrapper
ModuleNotFoundError: No module named 'CSV2DELTA'
[2023-06-01T18:22:32.821+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:22:32.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.024 seconds
[2023-06-01T18:23:02.947+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:02.947+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:23:02.948+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:02.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:02.949+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:02.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from CSV2DELTA.utils import CsvDagWrapper
ModuleNotFoundError: No module named 'CSV2DELTA'
[2023-06-01T18:23:02.949+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:02.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.018 seconds
[2023-06-01T18:23:17.019+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:17.023+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:23:17.024+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:17.024+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:17.025+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:17.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:23:17.026+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:17.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.027 seconds
[2023-06-01T18:23:43.878+0000] {processor.py:157} INFO - Started process (PID=23) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:43.879+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:23:43.880+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:43.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:43.881+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:23:43.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:23:43.882+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:23:43.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.050 seconds
[2023-06-01T18:24:13.989+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:13.990+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:24:13.990+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:24:13.990+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:13.992+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:24:13.991+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:24:13.992+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:14.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.047 seconds
[2023-06-01T18:24:44.091+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:44.093+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:24:44.094+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:24:44.094+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:44.095+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:24:44.095+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:24:44.095+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:24:44.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.046 seconds
[2023-06-01T18:25:14.248+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:14.251+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:25:14.251+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:25:14.251+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:14.252+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:25:14.252+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:25:14.253+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:14.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.046 seconds
[2023-06-01T18:25:44.403+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:44.406+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:25:44.407+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:25:44.407+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:44.408+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:25:44.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:25:44.408+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:25:44.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.049 seconds
[2023-06-01T18:26:14.566+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:14.568+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:26:14.569+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:26:14.569+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:14.570+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:26:14.570+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:26:14.570+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:14.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.046 seconds
[2023-06-01T18:26:44.725+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:44.727+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:26:44.728+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:26:44.728+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:44.729+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:26:44.729+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:26:44.730+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:26:44.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.046 seconds
[2023-06-01T18:27:14.881+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:27:14.882+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py for tasks to queue
[2023-06-01T18:27:14.882+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:27:14.882+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:27:14.884+0000] {logging_mixin.py:149} INFO - [2023-06-01T18:27:14.883+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py", line 9, in <module>
    from .utils import CsvDagWrapper
ImportError: attempted relative import with no known parent package
[2023-06-01T18:27:14.884+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py
[2023-06-01T18:27:14.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Csv2Delta/airflow/WrapperDag.py took 0.045 seconds
