[2023-06-20T16:48:47.673+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task scheduled__2023-06-20T15:00:00+00:00 [queued]>
[2023-06-20T16:48:47.678+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task scheduled__2023-06-20T15:00:00+00:00 [queued]>
[2023-06-20T16:48:47.678+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-20T16:48:47.688+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-20 15:00:00+00:00
[2023-06-20T16:48:47.691+0000] {standard_task_runner.py:57} INFO - Started process 64 to run task
[2023-06-20T16:48:47.693+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'oracle_connection_test_dag', 'execute_function_task', 'scheduled__2023-06-20T15:00:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/OracleTest_Dag.py', '--cfg-path', '/tmp/tmpge845zxa']
[2023-06-20T16:48:47.695+0000] {standard_task_runner.py:85} INFO - Job 372: Subtask execute_function_task
[2023-06-20T16:48:47.722+0000] {task_command.py:410} INFO - Running <TaskInstance: oracle_connection_test_dag.execute_function_task scheduled__2023-06-20T15:00:00+00:00 [running]> on host a1d2c9517f2c
[2023-06-20T16:48:47.762+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='oracle_connection_test_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-20T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-20T15:00:00+00:00'
[2023-06-20T16:48:47.763+0000] {logging_mixin.py:149} INFO - Creating Oracle Testing Class
[2023-06-20T16:48:47.763+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Python-Delta-Lake/Dags/OracleTest_Dag.py", line 46, in execute_function_task
    task.run_main()
AttributeError: 'OracleTestingClass' object has no attribute 'run_main'
[2023-06-20T16:48:47.767+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=oracle_connection_test_dag, task_id=execute_function_task, execution_date=20230620T150000, start_date=20230620T164847, end_date=20230620T164847
[2023-06-20T16:48:47.777+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 372 for task execute_function_task ('OracleTestingClass' object has no attribute 'run_main'; 64)
[2023-06-20T16:48:47.784+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-20T16:48:47.793+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
