[2023-06-29T20:57:54.388+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T20:57:53.669847+00:00 [queued]>
[2023-06-29T20:57:54.392+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T20:57:53.669847+00:00 [queued]>
[2023-06-29T20:57:54.393+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T20:57:54.402+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-29 20:57:53.669847+00:00
[2023-06-29T20:57:54.406+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2023-06-29T20:57:54.408+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore', 'execute_function_task', 'manual__2023-06-29T20:57:53.669847+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmpc4lg312f']
[2023-06-29T20:57:54.409+0000] {standard_task_runner.py:85} INFO - Job 576: Subtask execute_function_task
[2023-06-29T20:57:54.437+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore.execute_function_task manual__2023-06-29T20:57:53.669847+00:00 [running]> on host 3300c969268f
[2023-06-29T20:57:54.480+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T20:57:53.669847+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T20:57:53.669847+00:00'
[2023-06-29T20:57:54.483+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-06-29T20:57:54.483+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-06-29T20:57:54.483+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-06-29T20:57:56.655+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-06-29T20:57:56.656+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:50070')>.
[2023-06-29T20:57:56.657+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T20:57:56.661+0000] {logging_mixin.py:149} INFO - Cannot Establish HDFS connection: HTTPConnectionPool(host='localhost', port=50070): Max retries exceeded with url: /webhdfs/v1/?user.name=root&op=LISTSTATUS (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6dbb297be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-06-29T20:57:56.661+0000] {logging_mixin.py:149} INFO - HDFS Not Connected
[2023-06-29T20:57:56.661+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 4000 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-06-29T20:57:56.661+0000] {logging_mixin.py:149} INFO - Read on Mssql table failed: 'NoneType' object has no attribute 'read'
[2023-06-29T20:57:56.661+0000] {logging_mixin.py:149} INFO - Error Running Pipeline:'NoneType' object has no attribute 'toPandas'
[2023-06-29T20:57:56.661+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-29T20:57:56.669+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=Oracle_to_Filestore, task_id=execute_function_task, execution_date=20230629T205753, start_date=20230629T205754, end_date=20230629T205756
[2023-06-29T20:57:56.706+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T20:57:56.716+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
