[2023-06-20T18:38:43.227+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-20T18:38:42.584812+00:00 [queued]>
[2023-06-20T18:38:43.236+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-20T18:38:42.584812+00:00 [queued]>
[2023-06-20T18:38:43.236+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-20T18:38:43.263+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-20 18:38:42.584812+00:00
[2023-06-20T18:38:43.268+0000] {standard_task_runner.py:57} INFO - Started process 103 to run task
[2023-06-20T18:38:43.270+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'oracle_connection_test_dag', 'execute_function_task', 'manual__2023-06-20T18:38:42.584812+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/OracleTest_Dag.py', '--cfg-path', '/tmp/tmpymughq62']
[2023-06-20T18:38:43.272+0000] {standard_task_runner.py:85} INFO - Job 399: Subtask execute_function_task
[2023-06-20T18:38:43.303+0000] {task_command.py:410} INFO - Running <TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-20T18:38:42.584812+00:00 [running]> on host 0fef6b8b9a9f
[2023-06-20T18:38:43.345+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='oracle_connection_test_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-20T18:38:42.584812+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-20T18:38:42.584812+00:00'
[2023-06-20T18:38:43.346+0000] {logging_mixin.py:149} INFO - Creating Oracle Testing Class
[2023-06-20T18:40:00.949+0000] {logging_mixin.py:149} INFO - Error could not complete test:ORA-12154: TNS:could not resolve the connect identifier specified
[2023-06-20T18:40:00.949+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-20T18:40:01.050+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=oracle_connection_test_dag, task_id=execute_function_task, execution_date=20230620T183842, start_date=20230620T183843, end_date=20230620T184001
[2023-06-20T18:40:01.067+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-20T18:40:01.075+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
