[2023-06-09T18:08:36.103+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T18:08:34.890638+00:00 [queued]>
[2023-06-09T18:08:36.107+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T18:08:34.890638+00:00 [queued]>
[2023-06-09T18:08:36.107+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-09T18:08:36.113+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-09 18:08:34.890638+00:00
[2023-06-09T18:08:36.116+0000] {standard_task_runner.py:57} INFO - Started process 331 to run task
[2023-06-09T18:08:36.119+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wrapper_ex_dag', 'execute_function_task', 'manual__2023-06-09T18:08:34.890638+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/custom_dags/WrapperDag.py', '--cfg-path', '/tmp/tmp9hfcsg53']
[2023-06-09T18:08:36.120+0000] {standard_task_runner.py:85} INFO - Job 248: Subtask execute_function_task
[2023-06-09T18:08:36.147+0000] {task_command.py:410} INFO - Running <TaskInstance: wrapper_ex_dag.execute_function_task manual__2023-06-09T18:08:34.890638+00:00 [running]> on host c712b1d8680f
[2023-06-09T18:08:36.189+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wrapper_ex_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T18:08:34.890638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T18:08:34.890638+00:00'
[2023-06-09T18:08:36.190+0000] {CsvDagWrapper.py:22} INFO - CSV Delta Class Initialted
[2023-06-09T18:08:36.190+0000] {logging_mixin.py:149} INFO - Environment successfully parsed! Environment is Local
[2023-06-09T18:08:36.190+0000] {CsvDagWrapper.py:39} INFO - Environment successfully parsed! Environment is Local
[2023-06-09T18:08:36.190+0000] {logging_mixin.py:149} INFO - Table/s successfully parsed! Table:  ['CASE', 'CASE_PERS', 'PGM']
[2023-06-09T18:08:36.190+0000] {CsvDagWrapper.py:44} INFO - Table/s successfully parsed! Table:  ['CASE', 'CASE_PERS', 'PGM']
[2023-06-09T18:08:36.190+0000] {logging_mixin.py:149} INFO - Number of tables to be processed = 3
[2023-06-09T18:08:36.190+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Python-Delta-Lake/custom_dags/WrapperDag.py", line 46, in execute_function_task
    task.RunCsvToDelta("Local",["CASE","CASE_PERS","PGM"],False)
  File "/opt/airflow/dags/Python-Delta-Lake/Csv2Delta/CsvDagWrapper.py", line 56, in RunCsvToDelta
    logging.INFO(table_filter)
TypeError: 'int' object is not callable
[2023-06-09T18:08:36.194+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=wrapper_ex_dag, task_id=execute_function_task, execution_date=20230609T180834, start_date=20230609T180836, end_date=20230609T180836
[2023-06-09T18:08:36.200+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 248 for task execute_function_task ('int' object is not callable; 331)
[2023-06-09T18:08:36.210+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T18:08:36.219+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
